default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: <%= ENV.fetch("POSTGRESQL_HOST", "localhost") %>
  username: <%= ENV.fetch("POSTGRESQL_USERNAME", "postgres") %>
  password: <%= ENV.fetch("POSTGRESQL_PASSWORD", "") %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRESQL_DB_DEV", "checkcheck_development") %>


<% if ENV["DATABASE_URL"].present? %>
test:
  url: <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
<% else %>
test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000
<% end %>

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *primary_production
  queue:
    <<: *primary_production
  cable:
    <<: *primary_production
