name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lint:
    name: RuboCop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Lint code
        run: bin/rubocop -f github

  test:
    name: test (minitest + rspec)
    runs-on: ubuntu-latest
    needs: lint

    services:
      postgres:
        image: postgres:16
        ports: ["5432:5432"]
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: app_test
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:password@localhost:5432/app_test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Prepare DB
        run: bin/rails db:prepare

      - name: Run Minitest
        run: bin/rails test

      - name: Run RSpec (if spec/ exists)
        if: ${{ hashFiles('spec/**/*') != '' }}
        run: bundle exec rspec