# .github/workflows/rubocop.yml
name: RuboCop

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"     # ให้ตรงกับโปรเจกต์พี่
          bundler-cache: true     # auto bundle install + cache

      - name: Run RuboCop (strict)
        run: bundle exec rubocop --parallel --format github --fail-level refactor
